# Generated by Django 3.2.13 on 2022-06-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_user_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.TextField(default="", max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="profile_override",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="When set, user.profile will return this value instead of fetching a value from Auth0.",
            ),
        ),
    ]
