# Generated by Django 3.2.13 on 2022-07-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_unnecessary_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_override",
        ),
    ]
